services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - search-service

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo

  search-service:
    build: ./search-service
    ports:
      - "3002:3002"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      - elasticsearch

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"